name: CI
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        scala: ["2.12.8", "2.11.12"]
        spark: ["2.3.2", "2.4.0"]
        exclude:
          - scala: "2.12.8"
            spark: "2.3.2"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v5
      - name: Test
        run: sbt -Dspark.testVersion=${{ matrix.spark  }} ++${{ matrix.scala }} test
      - name: Assembly
        run: sbt ++${{ matrix.scala }} assembly
      - name: Scalastyle
        run: sbt ++${{ matrix.scala }} scalastyle "test:scalastyle"
  publish:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: GPG import
        run: openssl aes-256-cbc -pbkdf2 -k "${{ secrets.PGP_PASSPHRASE }}" -in private-key.pem.enc -out private-key.pem -d && gpg --import --no-tty --batch --yes private-key.pem
      - name: Publish
        run: sbt ci-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
