name: CI
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        scala: ["2.12.12"]
        spark: ["2.4.0", "3.0.0"]
        exclude:
          - scala: "2.11.12"
            spark: "3.0.0"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Cache SBT
        uses: actions/cache@v2
        with:
            path: |
                ~/.ivy2/cache
                ~/.sbt
            key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - uses: olafurpg/setup-scala@v10
      - name: Test
        run: sbt -Dspark.testVersion=${{ matrix.spark  }} ++${{ matrix.scala }} test
      - name: Assembly
        run: sbt ++${{ matrix.scala }} assembly
      - name: Scalastyle
        run: sbt ++${{ matrix.scala }} scalastyle "test:scalastyle"
